name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "feature" ]
  pull_request:
    branches: [ "main" ]



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    environment: TEST

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.10.0'
        registry-url: 'https://registry.yarnpkg.com'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn --cwd ./qeeps_test_application/ install
    - name: Test
      run: yarn --cwd ./qeeps_test_application/ test
      env:
        HOST: ${{ vars.HOST }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        MONGO_URL: ${{ secrets.MONGO_URL }}


  post-run:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Output message
        run: echo "Testing completed!"

  # Use a status check to mark the workflow as successful or unsuccessful
  # based on the status of the my-job job
  outputs:
    my-job-status: ${{ job.status }}
  if: ${{ needs.my-job.result == 'success' }}
  success:
  if: ${{ needs.my-job.result == 'failure' }}
  failure: