# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "feature" ]
  pull_request:
    branches: [ "main" ]



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.10]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.yarnpkg.com'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn --cwd /qeeps_test_application/ install
    - name: Test
      run: yarn --cwd /qeeps_test_application/ test